#!/usr/bin/env bash
config_error() {
    echo "Configuration error [${1}]: \"${2}\" ${3}"
}

parse_config() {
    errors=0

    [[ -n "$UCOLLAGE_LINES" ]] && ! is_natural "$UCOLLAGE_LINES" \
        && config_error "UCOLLAGE_LINES" "$UCOLLAGE_LINES" "is not a natural number" \
        && unset UCOLLAGE_LINES && errors=1
    [[ -n "$UCOLLAGE_COLUMNS" ]] && ! is_natural "$UCOLLAGE_COLUMNS" \
        && config_error "UCOLLAGE_COLUMNS" "$UCOLLAGE_COLUMNS" "is not a natural number" \
        && unset UCOLLAGE_COLUMNS && errors=1
    [[ -n "$UCOLLAGE_EXEC_PROMPT" ]] && [[ ! "$UCOLLAGE_EXEC_PROMPT" =~ ^(0|1)$ ]] \
        && config_error "UCOLLAGE_EXEC_PROMPT" "$UCOLLAGE_EXEC_PROMPT" " - valid values: 0, 1" \
        && unset UCOLLAGE_EXEC_PROMPT && errors=1
    [[ -n "$UCOLLAGE_SHOW_NAMES" ]] && [[ ! "$UCOLLAGE_SHOW_NAMES" =~ ^(0|1)$ ]] \
        && config_error "UCOLLAGE_SHOW_NAMES" "$UCOLLAGE_SHOW_NAMES" " - valid values: 0, 1" \
        && unset UCOLLAGE_SHOW_NAMES && errors=1

    [[ "$errors" -eq 1 ]] && read -rsN1
    unset errors
}

set_defaults() {
    fit_vertical=${UCOLLAGE_LINES:-3}
    fit_horizontal=${UCOLLAGE_COLUMNS:-4}
    tmp_dir=${UCOLLAGE_TMP_DIR:-"/tmp/ucollage"}
    exec_prompt=${UCOLLAGE_EXEC_PROMPT:-0}
    show_names=${UCOLLAGE_SHOW_NAMES:-1}
    error=""
    warning=""
}

help(){
    echo "Usage: ucollage [images]"
    echo "Controls:"
    echo "  n       get next batch of images"

    echo "  N       get previous batch of images"

    echo "  h       decrease number of columns by 1"

    echo "  j       decrease number of lines by 1"

    echo "  k       increase number of lines by 1"

    echo "  l       increase number of columns by 1"

    echo "  -       decrease both the numbers of columns and lines by 1"

    echo "  +/=     increase both the numbers of columns and lines by 1"

    echo "  s       input exact number for lines and columns"

    echo "  q       exit"

    echo "  m       enter monocle mode: show only one image"

    echo "  M       exit monocle mode"

    echo "  g       go to image number"

    echo "Monocle mode specific controls:"

    echo "  r       rotate image 90 degrees clockwise"

    echo "  R       rotate image 90 degrees counterclockwise"

    echo "  u       rotate image 180 degrees"

    echo "  x       execute command (placeholders are available for common substitutions)"
    echo "          %s - original image filename"
    echo "          %r - rotated image filename"
    echo "  c       rename image"
    exit
}

pre_read_images() {
    if [[ "$#" -gt 0 ]]
    then
        filelist=("$@")
    else
        filelist=(*)
    fi
    argc="${#filelist[@]}"
    images=()
    read_iter=0
}

read_images() {
    read_target="$1"
    readc=0
    while (( readc < read_target && read_iter < argc ))
    do
        file=${filelist[$read_iter]}
        [[ $(file --mime-type -b "$file") =~ ^image/.*$ ]] && images+=("$file") && (( readc += 1 )) \
        || printf "."
        (( read_iter += 1 ))
    done
    total="${#images[@]}"
}

clear_screen() {
    printf "\e[2J\e[?25l\e[H"
}

clear_status() {
    # clear only first three lines of screen
    printf "\e[?25l\e[H\e[2B\e[2K\e[1J\e[H"
}

clear_names() {
    # clear from 4th line and down 
    printf "\e[?25l\e[H\e[3B\e[2K\e[0J\e[H"
}

empty_messages() {
    success=""
    error=""
    warning=""
}

show_cursor() {
    printf "\e[?25h"
}

start_daemon() {
    fifo=$(mktemp --dry-run "${tmp_dir}/fifo-XXXXXXXXX")
    mkfifo "$fifo"
    ueberzug layer --parse bash --silent < "$fifo" &
    exec {colfd}> "$fifo"
}

stop_daemon() {
    exec {colfd}>&-
    rm "$fifo"
    [[ ! "$1" == "--no-exit" ]] && clear_screen && rm -rf "$tmp_dir" && show_cursor && stty echo && exit
}

restart_daemon() {
    stop_daemon --no-exit
    start_daemon
}

calculate_dimensions() {
    read -r lines columns < <(stty size)
    (( photo_columns = columns / fit_horizontal ))
    (( photo_lines = (lines - 3) / fit_vertical ))
    (( batch = fit_horizontal * fit_vertical ))
    (( show = total - start ))
    [[ "$show" -gt "$batch" ]] && show="$batch"
}

pad_sides() {
    length="${#current_name}"
    (( pads = photo_columns - length ))
    (( leftpad = pads / 2 ))
    (( rightpad = pads - leftpad ))
    for (( p = 0; p < leftpad; p++))
    do
        current_name=" $current_name"
    done
    for (( p = 0; p < rightpad; p++))
    do
        current_name+=" "
    done
}

show_batch() {
    cnt=0
    [[ "$show" -lt 1 ]] && return 1
    if [[ "$show_names" -eq 1 ]] && [[ "$show" -gt 1 ]]
    then
        # Substracting 3 lines is a hack. The names can be printed in
        # two lines, but ueberzug is not exact in its drawing on the 
        # terminal lines for different window sizes. 
        # So I give it some more room for error.
        (( draw_lines = photo_lines - 3 ))
        line_names=()
    else
        draw_lines="$photo_lines"
    fi
    for (( i = 0; i < fit_vertical; i++ ))
    do
        [[ "$show_names" -eq 1 ]] && [[ "$show" -gt 1 ]] && names=""
        for (( j = 0; j < fit_horizontal; j++, cnt++ ))
        do
            (( index = start + i * fit_horizontal + j))
            (( posx = j * photo_columns))
            (( posy = 3 + i * photo_lines))
            if [[ "$cnt" -ge "$show" ]]
            then
                assoc=( [action]=remove \
                        [identifier]="${fifo}${i}${j}" )
            else
                if [[ "$show_names" -eq 1 ]] && [[ "$show" -gt 1 ]]
                then
                    (( current_number = i * fit_horizontal + j + 1 ))
                    current_name="${current_number}: $(basename "${images[$index]}")"
                    (( max_length = photo_columns - 2 ))
                    current_name=${current_name:0:$max_length}
                    pad_sides
                    names+="$current_name"
                fi
                assoc=( [action]=add \
                        [identifier]="${fifo}${i}${j}" \
                        [path]="${images[$index]}" \
                        [width]="$photo_columns" \
                        [height]="$draw_lines" \
                        [x]="$posx" \
                        [y]="$posy" \
                        [scaler]=fit_contain )
            fi
            declare -p assoc > "$fifo"
        done
        [[ "$show_names" -eq 1 ]] && [[ "$show" -gt 1 ]] && line_names+=("$names")
    done
}

compute_batch() {
    case $1 in
        next)
            # There exists an edge case here when $show is less that
            # $batch, but we are not in the last batch of images
            # This can happen when we are loading the images in the background
            # and the user has changes the batch size with the 's' option
            # right after starting up.
            # So I change the initial
            #   (( start += batch))
            # to
            #   (( start += show))
            if (( start + batch < total ))
            then
                rm -f "$rotated_file"
                (( start += show ))
                (( show = total - start ))
                [[ "$show" -gt "$batch" ]] && show="$batch"
            else
                warning="End of files"
            fi
            ;;
        prev)
            [[ "$start" -le 0 ]] && warning="Start of files" && return
            rm -f "$rotated_file"
            (( start -= batch))
            # The below is useful in case of resizing
            # If I am in the second of batches of 10 and the
            # new window fits 20 then I don't want negative numbers
            [[ "$start" -lt 0 ]] && start=0
            show="$batch"
            ;;
    esac
}

get_input() {
    show_cursor
    printf "%s\e7" "$1"
    left=""
    right=""
    while true
    do
        printf "\e8\e[K"
        move=""
        [[ -n "$right" ]] && move="\e[${#right}D"
        printf "%s%s$move" "$left" "$right"
        read -rsN1 char
        read -rsN1 -t 0.0001 k1
        read -rsN1 -t 0.0001 k2
        read -rsN1 -t 0.0001 k3
        read -rsN1 -t 0.0001 k4
        key="${char}${k1}${k2}${k3}${k4}"
        case "$key" in
            $'\e[D') #left arrow press
                if [[ -n "$left" ]]
                then
                    right="${left: -1}$right";
                    left="${left:0:-1}"
                fi
                continue
                ;;
            $'\e[C') #right arrow press
                if [[ -n "$right" ]]
                then
                    left="$left${right:0:1}"
                    right="${right:1}";
                fi
                continue
                ;;
            $'\e[H'|$'\e[1~')
                right="${left}${right}"
                left=""
                continue
                ;;
            $'\e[F'|$'\e[4~')
                left="${left}${right}"
                right=""
                continue
                ;;
            $'\e[3~'|$'\e[P')
                [[ -n "$right" ]] && right="${right:1}"
                continue
                ;;
            $'\e')
                input="ESCAPE";
                break
                ;;
            $'\b'|$'\x7F')
                [[ -n "$left" ]] && left="${left:0:-1}"
                continue
                ;;
            $'\n')
                input="$left$right";
                break
                ;;
            [0-9]|[A-Z]|[a-z]|' '|[\/\:\;\|\<\>?+\-%._\\*@!$])
                left+="$key"
                continue
                ;;
            *)
                continue
                ;;
        esac
    done
}

is_natural() {
    [[ "$1" =~ ^[1-9][0-9]*$|^0+[1-9]+$ ]]
}

set_error() {
    error="(Error) Invalid value for $1: $2"
}

give_dimensions() {
    new_fit_vertical="$fit_vertical"
    new_fit_horizontal="$fit_horizontal"
    read -r lines columns < <(stty size)
    (( max_lines = lines -3 ))

    get_input "Give number of lines [default: $fit_vertical, max: $max_lines]: "
    [[ "$input" == "ESCAPE" ]] && return
    [[ -n "$input" ]] && ! is_natural "$input" && set_error lines "$input" && return
    [[ -n "$input" && ! "$input" -eq "$fit_vertical" ]] && new_fit_vertical="$input"

    printf "\n"
    get_input "Give number of columns [Default: $fit_horizontal, Max: $columns]: "
    [[ "$input" == "ESCAPE" ]] && return
    [[ -n "$input" ]] && ! is_natural "$input" && set_error columns "$input" && return
    [[ -n "$input" && ! "$input" -eq "$photo_columns" ]] && new_fit_horizontal="$input"
}

print_names() {
    read -r lines columns < <(stty size)
    separator=""
    for (( s = 0; s < columns; s++ ))
    do
        separator+="─"
    done
    l=${#line_names[@]}
    for (( i = 0; i < l; i++))
    do
        (( current_line = 2 + (i + 1) * photo_lines ))
        printf "\e[%s;1f" "$current_line"
        printf "\e[2K%s" "${line_names[$i]}"
        (( current_line += 1 ))
        printf "\e[%s;1f" "$current_line"
        printf "%s" "$separator"
    done
}

update_names() {
    clear_names
    [[ "$show_names" -eq 1 ]] && [[ "$show" -gt 1 ]] && print_names
}

redraw() {
    restart_daemon
    calculate_dimensions
    if [[ "$show" -eq 1 && -f "$rotated_file" ]]
    then
        assoc=( [action]=add \
                [identifier]="${fifo}00" \
                [path]="$rotated_file" \
                [width]="$photo_columns" \
                [height]="$photo_lines" \
                [x]="$posx" \
                [y]="$posy" \
                [scaler]=fit_contain )
        declare -p assoc > "$fifo"
    else
        show_batch
    fi
    update_names
}

maybe_redraw() {
    read -r lines columns < <(stty size)
    if (( new_fit_vertical != fit_vertical || new_fit_horizontal != fit_horizontal ))
    then
        (( new_fit_vertical > lines - 3 || new_fit_vertical < 1 )) \
            && set_error lines "$new_fit_vertical" && return
        (( new_fit_horizontal > columns || new_fit_horizontal < 1 )) \
            && set_error columns "$new_fit_horizontal" && return
        if [[ "$new_fit_vertical" -eq 1 && "$new_fit_horizontal" -eq 1 ]]
        then
            wide_vertical="$fit_vertical"
            wide_horizontal="$fit_horizontal"
        fi
        fit_vertical="$new_fit_vertical"
        fit_horizontal="$new_fit_horizontal"
        redraw
    fi
}

print_info() {
    info="[$fit_vertical x $fit_horizontal]"
    if [[ "$show" -gt 1 ]]
    then
        ((begin = start + 1))
        ((finish = begin + show - 1))
        info+=" - Photos [$begin - $finish] of $total"
    else
        ((begin = start + 1))
        info+=" - Photo $begin of $total - ${images[$start]}"
    fi
    printf "%s" "$info"
}

in_monocle() {
    [[ "$batch" -gt 1 ]] && warning="${1} option available for single images. Press [m] to enter monocle mode" && return 1
    return 0
}

rotate() {
    ! in_monocle "Rotate" && return
    ! command -v convert &> /dev/null && error="imagemagick not installed: required for rotation of images" && return
    ! command -v basename &> /dev/null && error="basename not installed: required for rotation of images" && return
    rotated_file="${tmp_dir}/rotated-$(basename "${images[$start]}")"
    [[ ! -f "$rotated_file" ]] && cp "${images[$start]}" "$rotated_file"
    convert -rotate "$1" "$rotated_file" "$rotated_file"
    assoc=( [action]=add \
            [identifier]="${fifo}00" \
            [path]="$rotated_file" \
            [width]="$photo_columns" \
            [height]="$photo_lines" \
            [x]="$posx" \
            [y]="$posy" \
            [scaler]=fit_contain )
    declare -p assoc > "$fifo"
}

eval_cmd() {
    if [[ "$exec_prompt" -eq 1 ]]
    then
        clear_status
        printf "%s? (press n/N/Esc to abort)" "$1"
        read -rsN1 ans
        if [[ ! "$ans" =~ ^(n|N)$ ]] && [[ ! "$ans" == $'\e' ]]
        then
            error=$(eval "$2" 2>&1 >/dev/null)
            [[ -z "$error" ]] && success="$3" && return
        fi
    else
        error=$(eval "$cmd" 2>&1 >/dev/null)
        [[ -z "$error" ]] && success="$3" && return
    fi
    return 1
}

execute() {
    ! in_monocle "Execute" && return
    get_input "Command (add %s for the current file): "
    [[ "$input" == "ESCAPE" ]] && return
    cmd=${input//%s/${images[$start]}}
    cmd=${cmd//%r/${rotated_file}}
    eval_cmd "Execute: \"${cmd}\"" "$cmd" "Succesful execution"
}

rename() {
    ! in_monocle "Rename" && return
    printf "Old name: %s\n" "${images[$start]}"
    get_input "New name: "
    [[ "$input" == "ESCAPE" ]] && return
    cmd="mv ${images[$start]} $input"
    eval_cmd "Rename to: \"${input}\"" "$cmd" "Succesfully renamed" && images[$start]="$input"
}

goto_image() {
    [[ "$show" -eq 1 ]] && return
    if [[ -n "$1" ]]
    then
        input="$1"
    else
        get_input "Go to: "
    fi
    [[ "$input" == "ESCAPE" ]] && return
    ! is_natural "$input" && set_error image "$input" && return
    [[ "$input" -gt "$show" ]] && set_error image "${input}: valid in range [1, $show]" && return
    (( start += input - 1 ))
    wide_vertical="$fit_vertical"
    wide_horizontal="$fit_horizontal"
    fit_vertical=1
    fit_horizontal=1
    redraw
}

update_status() {
    clear_status
    if [[ -n "$success" ]]
    then
        printf "\e[32m%s\e[m" "$success"
    elif [[ -n "$error" ]]
    then
        printf "\e[31m%s\e[m" "$error"
    elif [[ -n "$warning" ]]
    then
        printf "\e[33m%s\e[m" "$warning"
    else
        print_info
    fi
}

read_key() {
    while true
    do
        read -rsN1 -t 0.001 key
        case $key in
            q)
                stop_daemon
                ;;
            n)
                empty_messages
                compute_batch next
                show_batch
                update_status
                update_names
                ;;
            N)
                empty_messages
                compute_batch prev
                show_batch
                update_status
                update_names
                ;;
            s)
                stty echo
                empty_messages
                clear_status
                give_dimensions
                maybe_redraw
                update_status
                stty -echo
                ;;
            +|=)
                empty_messages
                (( new_fit_vertical = fit_vertical + 1 ))
                (( new_fit_horizontal = fit_horizontal + 1 ))
                maybe_redraw
                update_status
                ;;
            -)
                empty_messages
                (( new_fit_vertical = fit_vertical - 1 ))
                (( new_fit_horizontal = fit_horizontal -1 ))
                maybe_redraw
                update_status
                ;;
            m)
                empty_messages
                goto_image 1
                update_status
                ;;
            M)
                empty_messages
                if [[ "$show" -eq 1 ]]
                then
                    fit_vertical="$wide_vertical"
                    fit_horizontal="$wide_horizontal"
                    redraw
                fi
                update_status
                ;;
            k)
                empty_messages
                (( new_fit_vertical = fit_vertical + 1 ))
                (( new_fit_horizontal = fit_horizontal ))
                maybe_redraw
                update_status
                ;;
            j)
                empty_messages
                (( new_fit_vertical = fit_vertical - 1 ))
                (( new_fit_horizontal = fit_horizontal ))
                maybe_redraw
                update_status
                ;;
            l)
                empty_messages
                (( new_fit_vertical = fit_vertical ))
                (( new_fit_horizontal = fit_horizontal + 1 ))
                maybe_redraw
                update_status
                ;;
            h)
                empty_messages
                (( new_fit_vertical = fit_vertical ))
                (( new_fit_horizontal = fit_horizontal - 1 ))
                maybe_redraw
                update_status
                ;;
            r)
                empty_messages
                rotate 90
                update_status
                ;;
            R)
                empty_messages
                rotate -90
                update_status
                ;;
            u)
                empty_messages
                rotate 180
                update_status
                ;;
            x)
                stty echo
                empty_messages
                clear_status
                execute
                update_status
                stty -echo
                ;;
            c)
                stty echo
                empty_messages
                clear_status
                rename
                update_status
                stty -echo
                ;;
            g)
                stty echo
                empty_messages
                clear_status
                goto_image
                update_status
                stty -echo
                ;;
            $'\e'|$'\n')
                empty_messages
                update_status
                ;;
        esac
        [[ read_iter -gt "$argv" ]] && read_images "$batch"
    done
}

init() {
    start_daemon
    calculate_dimensions
    show_batch
    clear_screen
    update_status
    update_names
    read_key
}

! command -v ueberzug &> /dev/null && echo "Ueberzug not installed: ucollage dependency" && exit 1
parse_config
set_defaults
[[ ! -d "$tmp_dir" ]] && mkdir -p "$tmp_dir"
trap stop_daemon SIGINT
trap "redraw; update_status" SIGWINCH
stty -echo
[[ "$1" =~ ^-h$|^--help$ ]] && help
(( first_batch = fit_vertical * fit_horizontal ))
pre_read_images "$@"
read_images "$first_batch"
[[ "$total" -eq 0 ]] && echo "No images to show" && exit 1
start=0
declare -A assoc
init
